name: Semgrep Python Scan

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: ["master", "main"]
    paths:
      - '**.py'
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/python-scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List changed Python files
        id: changes
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.py$' || true
          else
            git diff --name-only HEAD~1 HEAD | grep '\.py$' || true
          fi

      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config "auto" \
            --config "p/python" \
            --config "p/security-audit" \
            --sarif > semgrep.sarif

      - name: Display findings
        run: cat semgrep.sarif